
CREATE DATABASE IF NOT EXISTS shipping;
USE shipping;

CREATE TABLE IF NOT EXISTS admins (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  isVerified BOOLEAN DEFAULT false,
  verificationToken VARCHAR(255),
  resetPasswordToken VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shipment_details (
  id INT PRIMARY KEY AUTO_INCREMENT,
  shipmentID VARCHAR(255) UNIQUE NOT NULL,
  senderName VARCHAR(255) NOT NULL,
  sendingAddress TEXT NOT NULL,
  receivingAddress TEXT NOT NULL,
  recipientName VARCHAR(255) NOT NULL,
  shipmentDescription TEXT,
  adminId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (adminId) REFERENCES admins(id)
);

CREATE TABLE IF NOT EXISTS shipment_statuses (
  id INT PRIMARY KEY AUTO_INCREMENT,
  status VARCHAR(255) NOT NULL,
  dateAndTime TIMESTAMP NOT NULL,
  carrierNote TEXT,
  requiresFee BOOLEAN DEFAULT false,
  feeInDollars DECIMAL(10,2),
  percentageNote VARCHAR(255),
  paymentStatus VARCHAR(255),
  supportingDocument VARCHAR(255),
  shipmentDetailsId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (shipmentDetailsId) REFERENCES shipment_details(id)
);
